twig:
    default_path: '%kernel.project_dir%/templates'
<<<<<<< HEAD
    form_themes: ['bootstrap_5_layout.html.twig']
=======
    
>>>>>>> origin/Gestion_ActivitéZZ

when@test:
    twig:
        strict_variables: true
<<<<<<< HEAD
=======
        
>>>>>>> origin/Gestion_ActivitéZZ
