twig:
    default_path: '%kernel.project_dir%/templates'
<<<<<<< HEAD
    
    
=======
    form_themes: ['bootstrap_5_layout.html.twig']

>>>>>>> 2ac1416d04ecfc7e00c75a64702ba6d465db601e
when@test:
    twig:
        strict_variables: true
