#path et controller doivent etres alignés sinon on aura une erreur
#Route de liste de tous les recettes
##############################_Recette_##############################

app_name_index:
  path: /recette_admin
  controller: App\Controller\NameController::index

app_name_new:
  path: /new_recette_admin
  controller: App\Controller\NameController::new

app_name_show:
  path: /{id}/recette_admin
  controller: App\Controller\NameController::show

app_name_edit:
  path: /{id}/edit_recette_admin
  controller: App\Controller\NameController::edit

app_name_delete:
  path: /{id}/delete_recette
  controller: App\Controller\NameController::delete

##############################_Plan_ nutritionnel_##############################
app_plan_nutrtionnel_index:
  path: /plan
  controller: App\Controller\PlanNutrtionnelController::index
  
app_plan_nutrtionnel_new:
  path: /new_planN
  controller: App\Controller\PlanNutrtionnelController::new
  
app_plan_nutrtionnel_show:
  path: /{id}/show_plan
  controller: App\Controller\PlanNutrtionnelController::show
  
app_plan_nutrtionnel_edit:
  path: /{id}/edit
  controller: App\Controller\PlanNutrtionnelController::edit

app_plan_nutrtionnel_delete:
  path: /{id}/delete_plan
  controller: App\Controller\PlanNutrtionnelController::delete

##############################_recette_User_ ##############################

app_reccete_user:
  path: /recette/user
  controller: App\Controller\RecceteUserController::index
  
app_user_reccette_plan:
  path: /recette_user
  controller: App\Controller\RecceteUserController::display_pics

   
app_user_recette_show:
  path: /{id}/recette_user
  controller: App\Controller\RecceteUserController::show_recette  


app_recipes_new:
  path: /new_recette_user
  controller: App\Controller\RecceteUserController::new

app_user_delete:
  path: /{id}/delete_recette_user
  controller: App\Controller\RecceteUserController::delete

#####################################Plan_nutritionnelle_user################################################
app_user_plan_nutrtionnel_new:
  path: /new/plan/user
  controller: App\Controller\PlanNutritionnelUserController::new
  
app_plan_nutritionnel_user:
  path: /plan/user
  controller: App\Controller\PlanNutritionnelUserController::index

app_user_plan_nutrtionnel_edit:
  path: /{id}/edit_user_plan
  controller: App\Controller\PlanNutritionnelUserController::edit

