<<<<<<< HEAD
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
=======
#home:
#   path: /home
 #   controller: App\Controller\HomeController::index
>>>>>>> 2ac1416d04ecfc7e00c75a64702ba6d465db601e
